// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// AddressInfo is the golang structure for table address_info.
type AddressInfo internal.AddressInfo

// Fill with you ideas below.
