// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// AdminInfo is the golang structure for table admin_info.
type AdminInfo internal.AdminInfo

// Fill with you ideas below.
