// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// ArticleInfo is the golang structure for table article_info.
type ArticleInfo internal.ArticleInfo

// Fill with you ideas below.
