// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// CartInfo is the golang structure for table cart_info.
type CartInfo internal.CartInfo

// Fill with you ideas below.
