// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// CategoryInfo is the golang structure for table category_info.
type CategoryInfo internal.CategoryInfo

// Fill with you ideas below.
