// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// CityInfo is the golang structure for table city_info.
type CityInfo internal.CityInfo

// Fill with you ideas below.
