// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// CollectionInfo is the golang structure for table collection_info.
type CollectionInfo internal.CollectionInfo

// Fill with you ideas below.
