// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// CommentInfo is the golang structure for table comment_info.
type CommentInfo internal.CommentInfo

// Fill with you ideas below.
