// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// ConsigneeInfo is the golang structure for table consignee_info.
type ConsigneeInfo internal.ConsigneeInfo

// Fill with you ideas below.
