// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// CouponInfo is the golang structure for table coupon_info.
type CouponInfo internal.CouponInfo

// Fill with you ideas below.
