// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// GoodsOptionsInfo is the golang structure for table goods_options_info.
type GoodsOptionsInfo internal.GoodsOptionsInfo

// Fill with you ideas below.
