// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// GoodsInfo is the golang structure for table goods_info.
type GoodsInfo internal.GoodsInfo

// Fill with you ideas below.
