// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// OrderGoodsInfo is the golang structure for table order_goods_info.
type OrderGoodsInfo internal.OrderGoodsInfo

// Fill with you ideas below.
