// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// OrderInfo is the golang structure for table order_info.
type OrderInfo internal.OrderInfo

// Fill with you ideas below.
