// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// PermissionInfo is the golang structure for table permission_info.
type PermissionInfo internal.PermissionInfo

// Fill with you ideas below.
