// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// PraiseInfo is the golang structure for table praise_info.
type PraiseInfo internal.PraiseInfo

// Fill with you ideas below.
