// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// RefundInfo is the golang structure for table refund_info.
type RefundInfo internal.RefundInfo

// Fill with you ideas below.
