// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// RolePermissionInfo is the golang structure for table role_permission_info.
type RolePermissionInfo internal.RolePermissionInfo

// Fill with you ideas below.
