// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// RoleInfo is the golang structure for table role_info.
type RoleInfo internal.RoleInfo

// Fill with you ideas below.
