// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// RolesPermissionInfo is the golang structure for table roles_permission_info.
type RolesPermissionInfo internal.RolesPermissionInfo

// Fill with you ideas below.
