// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// ShoppingCartInfo is the golang structure for table shopping_cart_info.
type ShoppingCartInfo internal.ShoppingCartInfo

// Fill with you ideas below.
