// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// UserCouponInfo is the golang structure for table user_coupon_info.
type UserCouponInfo internal.UserCouponInfo

// Fill with you ideas below.
