// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"shop/app/model/internal"
)

// UserInfo is the golang structure for table user_info.
type UserInfo internal.UserInfo

// Fill with you ideas below.
