// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// ArticleInfo is the golang structure for table article_info.
type ArticleInfo struct {
	Id        int         `orm:"id,primary" json:"id"`        //
	UserId    int         `orm:"user_id"    json:"userId"`    // 作者id
	Title     string      `orm:"title"      json:"title"`     // 标题
	Desc      string      `orm:"desc"       json:"desc"`      // 摘要
	PicUrl    string      `orm:"pic_url"    json:"picUrl"`    // 封面图
	IsAdmin   int         `orm:"is_admin"   json:"isAdmin"`   // 是否官方发布
	Praise    int         `orm:"praise"     json:"praise"`    // 点赞数
	Detail    string      `orm:"detail"     json:"detail"`    // 文章详情
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //
	DeletedAt *gtime.Time `orm:"deleted_at" json:"deletedAt"` //
}
