// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// CollectionInfo is the golang structure for table collection_info.
type CollectionInfo struct {
	Id        int         `orm:"id,primary" json:"id"`        //
	UserId    int         `orm:"user_id"    json:"userId"`    //
	ObjectId  int         `orm:"object_id"  json:"objectId"`  //
	Type      int         `orm:"type"       json:"type"`      // 收藏类型：1商品 2文章
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //
}
