// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// CommentInfo is the golang structure for table comment_info.
type CommentInfo struct {
	Id        int         `orm:"id,primary" json:"id"`        //
	ParentId  int         `orm:"parent_id"  json:"parentId"`  // 父级评论id
	UserId    int         `orm:"user_id"    json:"userId"`    //
	ObjectId  int         `orm:"object_id"  json:"objectId"`  //
	Type      int         `orm:"type"       json:"type"`      // 评论类型：1商品 2文章
	Content   string      `orm:"content"    json:"content"`   // 评论内容
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //
	DeletedAt *gtime.Time `orm:"deleted_at" json:"deletedAt"` //
}
