// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// ConsigneeInfo is the golang structure for table consignee_info.
type ConsigneeInfo struct {
	Id        int         `orm:"id,primary" json:"id"`        // 收货地址表
	UserId    int         `orm:"user_id"    json:"userId"`    //
	IsDefault int         `orm:"is_default" json:"isDefault"` // 默认地址1  非默认0
	Name      string      `orm:"name"       json:"name"`      //
	Phone     string      `orm:"phone"      json:"phone"`     //
	Province  string      `orm:"province"   json:"province"`  //
	City      string      `orm:"city"       json:"city"`      //
	Town      string      `orm:"town"       json:"town"`      // 县区
	Street    string      `orm:"street"     json:"street"`    // 街道乡镇
	Detail    string      `orm:"detail"     json:"detail"`    // 地址详情
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //
	DeletedAt *gtime.Time `orm:"deleted_at" json:"deletedAt"` //
}
