// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// CouponInfo is the golang structure for table coupon_info.
type CouponInfo struct {
	Id         int         `orm:"id,primary"  json:"id"`         //
	Name       string      `orm:"name"        json:"name"`       //
	Price      int         `orm:"price"       json:"price"`      // 优惠前面值 单位分
	GoodsIds   string      `orm:"goods_ids"   json:"goodsIds"`   // 关联使用的goods_ids  逗号分隔
	CategoryId int         `orm:"category_id" json:"categoryId"` // 关联使用的分类id
	CreatedAt  *gtime.Time `orm:"created_at"  json:"createdAt"`  //
	UpdatedAt  *gtime.Time `orm:"updated_at"  json:"updatedAt"`  //
	DeletedAt  *gtime.Time `orm:"deleted_at"  json:"deletedAt"`  //
}
