// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// GoodsOptionsInfo is the golang structure for table goods_options_info.
type GoodsOptionsInfo struct {
	Id        int         `orm:"id,primary" json:"id"`        //
	GoodsId   int         `orm:"goods_id"   json:"goodsId"`   // 商品id
	PicUrl    string      `orm:"pic_url"    json:"picUrl"`    // 图片
	Name      string      `orm:"name"       json:"name"`      // 商品名称
	Price     int         `orm:"price"      json:"price"`     // 价格 单位分
	Stock     int         `orm:"stock"      json:"stock"`     // 库存
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //
	DeletedAt *gtime.Time `orm:"deleted_at" json:"deletedAt"` //
}
