// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// OrderInfo is the golang structure for table order_info.
type OrderInfo struct {
	Id               int         `orm:"id,primary"        json:"id"`               //
	Number           string      `orm:"number"            json:"number"`           // 订单编号
	UserId           int         `orm:"user_id"           json:"userId"`           // 用户id
	PayType          int         `orm:"pay_type"          json:"payType"`          // 支付方式 1微信 2支付宝 3云闪付
	CreatedAt        *gtime.Time `orm:"created_at"        json:"createdAt"`        //
	UpdatedAt        *gtime.Time `orm:"updated_at"        json:"updatedAt"`        //
	Remark           string      `orm:"remark"            json:"remark"`           // 备注
	PayAt            *gtime.Time `orm:"pay_at"            json:"payAt"`            // 支付时间
	Status           int         `orm:"status"            json:"status"`           // 订单状态： 1待支付 2已支付待发货 3已发货 4已收货待评价
	ConsigneeName    string      `orm:"consignee_name"    json:"consigneeName"`    // 收货人姓名
	ConsigneePhone   string      `orm:"consignee_phone"   json:"consigneePhone"`   // 收货人手机号
	ConsigneeAddress string      `orm:"consignee_address" json:"consigneeAddress"` // 收货人详细地址
	Price            int         `orm:"price"             json:"price"`            // 订单金额 单位分
	CouponPrice      int         `orm:"coupon_price"      json:"couponPrice"`      // 优惠券金额 单位分
	ActualPrice      int         `orm:"actual_price"      json:"actualPrice"`      // 实际支付金额 单位分
}
