// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// PraiseInfo is the golang structure for table praise_info.
type PraiseInfo struct {
	Id        int         `orm:"id,primary" json:"id"`        // 点赞表
	UserId    int         `orm:"user_id"    json:"userId"`    //
	Type      int         `orm:"type"       json:"type"`      // 点赞类型 1商品 2文章
	ObjectId  int         `orm:"object_id"  json:"objectId"`  // 点赞对象id 方便后期扩展
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //
}
