// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// RolePermissionInfo is the golang structure for table role_permission_info.
type RolePermissionInfo struct {
	Id           int         `orm:"id,primary"    json:"id"`           //
	RoleId       int         `orm:"role_id"       json:"roleId"`       // 角色id
	PermissionId int         `orm:"permission_id" json:"permissionId"` // 权限id
	CreatedAt    *gtime.Time `orm:"created_at"    json:"createdAt"`    //
	UpdatedAt    *gtime.Time `orm:"updated_at"    json:"updatedAt"`    //
}
