// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// RolesPermissionInfo is the golang structure for table roles_permission_info.
type RolesPermissionInfo struct {
	Id           int         `orm:"id,primary"    json:"id"`           //
	RolesId      int         `orm:"roles_id"      json:"rolesId"`      // 角色id
	PermissionId int         `orm:"permission_id" json:"permissionId"` // 权限id
	CreatedAt    *gtime.Time `orm:"created_at"    json:"createdAt"`    //
	UpdatedAt    *gtime.Time `orm:"updated_at"    json:"updatedAt"`    //
}
