// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// RotationInfo is the golang structure for table rotation_info.
type RotationInfo struct {
	Id        int         `orm:"id,primary" json:"id"`        //
	PicUrl    string      `orm:"pic_url"    json:"picUrl"`    // 轮播图片
	Link      string      `orm:"link"       json:"link"`      // 跳转链接
	Sort      int         `orm:"sort"       json:"sort"`      // 排序字段
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //
	DeletedAt *gtime.Time `orm:"deleted_at" json:"deletedAt"` //
}
