// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// UserCouponInfo is the golang structure for table user_coupon_info.
type UserCouponInfo struct {
	Id        int         `orm:"id,primary" json:"id"`        // 用户优惠券表
	UserId    int         `orm:"user_id"    json:"userId"`    //
	CouponId  int         `orm:"coupon_id"  json:"couponId"`  //
	Status    int         `orm:"status"     json:"status"`    // 状态：1可用 2已用 3过期
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updatedAt"` //
	DeletedAt *gtime.Time `orm:"deleted_at" json:"deletedAt"` //
}
