// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// UserInfo is the golang structure for table user_info.
type UserInfo struct {
	Id           int         `orm:"id,primary"    json:"id"`           //
	Name         string      `orm:"name"          json:"name"`         // 用户名
	Avatar       string      `orm:"avatar"        json:"avatar"`       // 头像
	Password     string      `orm:"password"      json:"password"`     //
	UserSalt     string      `orm:"user_salt"     json:"userSalt"`     // 加密盐 生成密码用
	Sex          int         `orm:"sex"           json:"sex"`          // 1男 2女 0未知
	Status       int         `orm:"status"        json:"status"`       // 1正常 2拉黑
	Sign         string      `orm:"sign"          json:"sign"`         // 个性签名
	SecretAnswer string      `orm:"secret_answer" json:"secretAnswer"` // 密保问题的答案
	CreatedAt    *gtime.Time `orm:"created_at"    json:"createdAt"`    //
	UpdatedAt    *gtime.Time `orm:"updated_at"    json:"updatedAt"`    //
	DeletedAt    *gtime.Time `orm:"deleted_at"    json:"deletedAt"`    //
}
