// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"shop/app/dao/internal"
)

// cartInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type cartInfoDao struct {
	*internal.CartInfoDao
}

var (
	// CartInfo is globally public accessible object for table cart_info operations.
	CartInfo cartInfoDao
)

func init() {
	CartInfo = cartInfoDao{
		internal.NewCartInfoDao(),
	}
}

// Fill with you ideas below.
