// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"shop/app/dao/internal"
)

// cityInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type cityInfoDao struct {
	*internal.CityInfoDao
}

var (
	// CityInfo is globally public accessible object for table city_info operations.
	CityInfo cityInfoDao
)

func init() {
	CityInfo = cityInfoDao{
		internal.NewCityInfoDao(),
	}
}

// Fill with you ideas below.
