// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"shop/app/dao/internal"
)

// commentInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type commentInfoDao struct {
	*internal.CommentInfoDao
}

var (
	// CommentInfo is globally public accessible object for table comment_info operations.
	CommentInfo commentInfoDao
)

func init() {
	CommentInfo = commentInfoDao{
		internal.NewCommentInfoDao(),
	}
}

// Fill with you ideas below.
