// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"shop/app/dao/internal"
)

// consigneeInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type consigneeInfoDao struct {
	*internal.ConsigneeInfoDao
}

var (
	// ConsigneeInfo is globally public accessible object for table consignee_info operations.
	ConsigneeInfo consigneeInfoDao
)

func init() {
	ConsigneeInfo = consigneeInfoDao{
		internal.NewConsigneeInfoDao(),
	}
}

// Fill with you ideas below.
