// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"shop/app/dao/internal"
)

// couponInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type couponInfoDao struct {
	*internal.CouponInfoDao
}

var (
	// CouponInfo is globally public accessible object for table coupon_info operations.
	CouponInfo couponInfoDao
)

func init() {
	CouponInfo = couponInfoDao{
		internal.NewCouponInfoDao(),
	}
}

// Fill with you ideas below.
