// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"shop/app/dao/internal"
)

// goodsInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type goodsInfoDao struct {
	*internal.GoodsInfoDao
}

var (
	// GoodsInfo is globally public accessible object for table goods_info operations.
	GoodsInfo goodsInfoDao
)

func init() {
	GoodsInfo = goodsInfoDao{
		internal.NewGoodsInfoDao(),
	}
}

// Fill with you ideas below.
