// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"shop/app/dao/internal"
)

// goodsOptionsInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type goodsOptionsInfoDao struct {
	*internal.GoodsOptionsInfoDao
}

var (
	// GoodsOptionsInfo is globally public accessible object for table goods_options_info operations.
	GoodsOptionsInfo goodsOptionsInfoDao
)

func init() {
	GoodsOptionsInfo = goodsOptionsInfoDao{
		internal.NewGoodsOptionsInfoDao(),
	}
}

// Fill with you ideas below.
