// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"shop/app/dao/internal"
)

// permissionInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type permissionInfoDao struct {
	*internal.PermissionInfoDao
}

var (
	// PermissionInfo is globally public accessible object for table permission_info operations.
	PermissionInfo permissionInfoDao
)

func init() {
	PermissionInfo = permissionInfoDao{
		internal.NewPermissionInfoDao(),
	}
}

// Fill with you ideas below.
