// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"shop/app/dao/internal"
)

// refundInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type refundInfoDao struct {
	*internal.RefundInfoDao
}

var (
	// RefundInfo is globally public accessible object for table refund_info operations.
	RefundInfo refundInfoDao
)

func init() {
	RefundInfo = refundInfoDao{
		internal.NewRefundInfoDao(),
	}
}

// Fill with you ideas below.
