// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"shop/app/dao/internal"
)

// rolePermissionInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type rolePermissionInfoDao struct {
	*internal.RolePermissionInfoDao
}

var (
	// RolePermissionInfo is globally public accessible object for table role_permission_info operations.
	RolePermissionInfo rolePermissionInfoDao
)

func init() {
	RolePermissionInfo = rolePermissionInfoDao{
		internal.NewRolePermissionInfoDao(),
	}
}

// Fill with you ideas below.
