// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"shop/app/dao/internal"
)

// rotationInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type rotationInfoDao struct {
	*internal.RotationInfoDao
}

var (
	// RotationInfo is globally public accessible object for table rotation_info operations.
	RotationInfo rotationInfoDao
)

func init() {
	RotationInfo = rotationInfoDao{
		internal.NewRotationInfoDao(),
	}
}

// Fill with you ideas below.
