// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"shop/app/dao/internal"
)

// shoppingCartInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type shoppingCartInfoDao struct {
	*internal.ShoppingCartInfoDao
}

var (
	// ShoppingCartInfo is globally public accessible object for table shopping_cart_info operations.
	ShoppingCartInfo shoppingCartInfoDao
)

func init() {
	ShoppingCartInfo = shoppingCartInfoDao{
		internal.NewShoppingCartInfoDao(),
	}
}

// Fill with you ideas below.
