// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"shop/app/dao/internal"
)

// userCouponInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type userCouponInfoDao struct {
	*internal.UserCouponInfoDao
}

var (
	// UserCouponInfo is globally public accessible object for table user_coupon_info operations.
	UserCouponInfo userCouponInfoDao
)

func init() {
	UserCouponInfo = userCouponInfoDao{
		internal.NewUserCouponInfoDao(),
	}
}

// Fill with you ideas below.
