// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AddressInfo is the golang structure for table address_info.
type AddressInfo struct {
	Id        int         `json:"id"        ` //
	Name      string      `json:"name"      ` //
	Pid       int         `json:"pid"       ` //
	Status    int         `json:"status"    ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
