// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// AdminInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type AdminInfoDao struct {
	gmvc.M                   // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB           // DB is the raw underlying database management object.
	Table   string           // Table is the table name of the DAO.
	Columns adminInfoColumns // Columns contains all the columns of Table that for convenient usage.
}

// AdminInfoColumns defines and stores column names for table admin_info.
type adminInfoColumns struct {
	Id         string //
	Name       string // 用户名
	Password   string // 密码
	Permission string // 权限
	CreatedAt  string //
	UpdatedAt  string //
	DeletedAt  string //
	UserSalt   string // 加密盐
}

func NewAdminInfoDao() *AdminInfoDao {
	return &AdminInfoDao{
		M:     g.DB("default").Model("admin_info").Safe(),
		DB:    g.DB("default"),
		Table: "admin_info",
		Columns: adminInfoColumns{
			Id:         "id",
			Name:       "name",
			Password:   "password",
			Permission: "permission",
			CreatedAt:  "created_at",
			UpdatedAt:  "updated_at",
			DeletedAt:  "deleted_at",
			UserSalt:   "user_salt",
		},
	}
}
