// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// CartInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type CartInfoDao struct {
	gmvc.M                  // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB          // DB is the raw underlying database management object.
	Table   string          // Table is the table name of the DAO.
	Columns cartInfoColumns // Columns contains all the columns of Table that for convenient usage.
}

// CartInfoColumns defines and stores column names for table cart_info.
type cartInfoColumns struct {
	Id        string // 购物车表
	UserId    string //
	GoodsId   string //
	Count     string // 商品数量
	CreatedAt string //
	UpdatedAt string //
	DeletedAt string //
}

func NewCartInfoDao() *CartInfoDao {
	return &CartInfoDao{
		M:     g.DB("default").Model("cart_info").Safe(),
		DB:    g.DB("default"),
		Table: "cart_info",
		Columns: cartInfoColumns{
			Id:        "id",
			UserId:    "user_id",
			GoodsId:   "goods_id",
			Count:     "count",
			CreatedAt: "created_at",
			UpdatedAt: "updated_at",
			DeletedAt: "deleted_at",
		},
	}
}
