// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// CityInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type CityInfoDao struct {
	gmvc.M                  // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB          // DB is the raw underlying database management object.
	Table   string          // Table is the table name of the DAO.
	Columns cityInfoColumns // Columns contains all the columns of Table that for convenient usage.
}

// CityInfoColumns defines and stores column names for table city_info.
type cityInfoColumns struct {
	Id        string //
	Name      string //
	Pid       string //
	Status    string //
	UpdatedAt string //
}

func NewCityInfoDao() *CityInfoDao {
	return &CityInfoDao{
		M:     g.DB("default").Model("city_info").Safe(),
		DB:    g.DB("default"),
		Table: "city_info",
		Columns: cityInfoColumns{
			Id:        "id",
			Name:      "name",
			Pid:       "pid",
			Status:    "status",
			UpdatedAt: "updated_at",
		},
	}
}
