// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// CollectionInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type CollectionInfoDao struct {
	gmvc.M                        // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB                // DB is the raw underlying database management object.
	Table   string                // Table is the table name of the DAO.
	Columns collectionInfoColumns // Columns contains all the columns of Table that for convenient usage.
}

// CollectionInfoColumns defines and stores column names for table collection_info.
type collectionInfoColumns struct {
	Id        string //
	UserId    string //
	ObjectId  string //
	Type      string // 收藏类型：1商品 2文章
	CreatedAt string //
	UpdatedAt string //
}

func NewCollectionInfoDao() *CollectionInfoDao {
	return &CollectionInfoDao{
		M:     g.DB("default").Model("collection_info").Safe(),
		DB:    g.DB("default"),
		Table: "collection_info",
		Columns: collectionInfoColumns{
			Id:        "id",
			UserId:    "user_id",
			ObjectId:  "object_id",
			Type:      "type",
			CreatedAt: "created_at",
			UpdatedAt: "updated_at",
		},
	}
}
