// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// GoodsInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type GoodsInfoDao struct {
	gmvc.M                   // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB           // DB is the raw underlying database management object.
	Table   string           // Table is the table name of the DAO.
	Columns goodsInfoColumns // Columns contains all the columns of Table that for convenient usage.
}

// GoodsInfoColumns defines and stores column names for table goods_info.
type goodsInfoColumns struct {
	Id               string //
	PicUrl           string // 图片
	Name             string // 商品名称
	Price            string // 价格 单位分
	Level1CategoryId string // 1级分类id
	Level2CategoryId string // 2级分类id
	Level3CategoryId string // 3级分类id
	Brand            string // 品牌
	CouponId         string // 优惠券id
	Stock            string // 库存
	Sale             string // 销量
	Tags             string // 标签
	DetailInfo       string // 商品详情
	CreatedAt        string //
	UpdatedAt        string //
	DeletedAt        string //
}

func NewGoodsInfoDao() *GoodsInfoDao {
	return &GoodsInfoDao{
		M:     g.DB("default").Model("goods_info").Safe(),
		DB:    g.DB("default"),
		Table: "goods_info",
		Columns: goodsInfoColumns{
			Id:               "id",
			PicUrl:           "pic_url",
			Name:             "name",
			Price:            "price",
			Level1CategoryId: "level1_category_id",
			Level2CategoryId: "level2_category_id",
			Level3CategoryId: "level3_category_id",
			Brand:            "brand",
			CouponId:         "coupon_id",
			Stock:            "stock",
			Sale:             "sale",
			Tags:             "tags",
			DetailInfo:       "detail_info",
			CreatedAt:        "created_at",
			UpdatedAt:        "updated_at",
			DeletedAt:        "deleted_at",
		},
	}
}
