// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// GoodsOptionsInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type GoodsOptionsInfoDao struct {
	gmvc.M                          // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB                  // DB is the raw underlying database management object.
	Table   string                  // Table is the table name of the DAO.
	Columns goodsOptionsInfoColumns // Columns contains all the columns of Table that for convenient usage.
}

// GoodsOptionsInfoColumns defines and stores column names for table goods_options_info.
type goodsOptionsInfoColumns struct {
	Id        string //
	GoodsId   string // 商品id
	PicUrl    string // 图片
	Name      string // 商品名称
	Price     string // 价格 单位分
	Stock     string // 库存
	CreatedAt string //
	UpdatedAt string //
	DeletedAt string //
}

func NewGoodsOptionsInfoDao() *GoodsOptionsInfoDao {
	return &GoodsOptionsInfoDao{
		M:     g.DB("default").Model("goods_options_info").Safe(),
		DB:    g.DB("default"),
		Table: "goods_options_info",
		Columns: goodsOptionsInfoColumns{
			Id:        "id",
			GoodsId:   "goods_id",
			PicUrl:    "pic_url",
			Name:      "name",
			Price:     "price",
			Stock:     "stock",
			CreatedAt: "created_at",
			UpdatedAt: "updated_at",
			DeletedAt: "deleted_at",
		},
	}
}
