// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// PermissionInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type PermissionInfoDao struct {
	gmvc.M                        // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB                // DB is the raw underlying database management object.
	Table   string                // Table is the table name of the DAO.
	Columns permissionInfoColumns // Columns contains all the columns of Table that for convenient usage.
}

// PermissionInfoColumns defines and stores column names for table permission_info.
type permissionInfoColumns struct {
	Id        string //
	Name      string // 权限名称
	Path      string // 路径
	CreatedAt string //
	UpdatedAt string //
	DeletedAt string //
}

func NewPermissionInfoDao() *PermissionInfoDao {
	return &PermissionInfoDao{
		M:     g.DB("default").Model("permission_info").Safe(),
		DB:    g.DB("default"),
		Table: "permission_info",
		Columns: permissionInfoColumns{
			Id:        "id",
			Name:      "name",
			Path:      "path",
			CreatedAt: "created_at",
			UpdatedAt: "updated_at",
			DeletedAt: "deleted_at",
		},
	}
}
