// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// PraiseInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type PraiseInfoDao struct {
	gmvc.M                    // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB            // DB is the raw underlying database management object.
	Table   string            // Table is the table name of the DAO.
	Columns praiseInfoColumns // Columns contains all the columns of Table that for convenient usage.
}

// PraiseInfoColumns defines and stores column names for table praise_info.
type praiseInfoColumns struct {
	Id        string // 点赞表
	UserId    string //
	Type      string // 点赞类型 1商品 2文章
	ObjectId  string // 点赞对象id 方便后期扩展
	CreatedAt string //
	UpdatedAt string //
}

func NewPraiseInfoDao() *PraiseInfoDao {
	return &PraiseInfoDao{
		M:     g.DB("default").Model("praise_info").Safe(),
		DB:    g.DB("default"),
		Table: "praise_info",
		Columns: praiseInfoColumns{
			Id:        "id",
			UserId:    "user_id",
			Type:      "type",
			ObjectId:  "object_id",
			CreatedAt: "created_at",
			UpdatedAt: "updated_at",
		},
	}
}
