// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// RoleInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type RoleInfoDao struct {
	gmvc.M                  // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB          // DB is the raw underlying database management object.
	Table   string          // Table is the table name of the DAO.
	Columns roleInfoColumns // Columns contains all the columns of Table that for convenient usage.
}

// RoleInfoColumns defines and stores column names for table role_info.
type roleInfoColumns struct {
	Id        string //
	Name      string // 角色名称
	Desc      string // 描述
	CreatedAt string //
	UpdatedAt string //
	DeletedAt string //
}

func NewRoleInfoDao() *RoleInfoDao {
	return &RoleInfoDao{
		M:     g.DB("default").Model("role_info").Safe(),
		DB:    g.DB("default"),
		Table: "role_info",
		Columns: roleInfoColumns{
			Id:        "id",
			Name:      "name",
			Desc:      "desc",
			CreatedAt: "created_at",
			UpdatedAt: "updated_at",
			DeletedAt: "deleted_at",
		},
	}
}
