// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// RolePermissionInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type RolePermissionInfoDao struct {
	gmvc.M                            // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB                    // DB is the raw underlying database management object.
	Table   string                    // Table is the table name of the DAO.
	Columns rolePermissionInfoColumns // Columns contains all the columns of Table that for convenient usage.
}

// RolePermissionInfoColumns defines and stores column names for table role_permission_info.
type rolePermissionInfoColumns struct {
	Id           string //
	RoleId       string // 角色id
	PermissionId string // 权限id
	CreatedAt    string //
	UpdatedAt    string //
}

func NewRolePermissionInfoDao() *RolePermissionInfoDao {
	return &RolePermissionInfoDao{
		M:     g.DB("default").Model("role_permission_info").Safe(),
		DB:    g.DB("default"),
		Table: "role_permission_info",
		Columns: rolePermissionInfoColumns{
			Id:           "id",
			RoleId:       "role_id",
			PermissionId: "permission_id",
			CreatedAt:    "created_at",
			UpdatedAt:    "updated_at",
		},
	}
}
