// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// RotationInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type RotationInfoDao struct {
	gmvc.M                      // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB              // DB is the raw underlying database management object.
	Table   string              // Table is the table name of the DAO.
	Columns rotationInfoColumns // Columns contains all the columns of Table that for convenient usage.
}

// RotationInfoColumns defines and stores column names for table rotation_info.
type rotationInfoColumns struct {
	Id        string //
	PicUrl    string // 轮播图片
	Link      string // 跳转链接
	Sort      string // 排序字段
	CreatedAt string //
	UpdatedAt string //
	DeletedAt string //
}

func NewRotationInfoDao() *RotationInfoDao {
	return &RotationInfoDao{
		M:     g.DB("default").Model("rotation_info").Safe(),
		DB:    g.DB("default"),
		Table: "rotation_info",
		Columns: rotationInfoColumns{
			Id:        "id",
			PicUrl:    "pic_url",
			Link:      "link",
			Sort:      "sort",
			CreatedAt: "created_at",
			UpdatedAt: "updated_at",
			DeletedAt: "deleted_at",
		},
	}
}
