// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// ShoppingCartInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type ShoppingCartInfoDao struct {
	gmvc.M                          // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB                  // DB is the raw underlying database management object.
	Table   string                  // Table is the table name of the DAO.
	Columns shoppingCartInfoColumns // Columns contains all the columns of Table that for convenient usage.
}

// ShoppingCartInfoColumns defines and stores column names for table shopping_cart_info.
type shoppingCartInfoColumns struct {
	Id        string // 购物车表
	UserId    string //
	GoodsId   string //
	Count     string // 商品数量
	CreatedAt string //
	UpdatedAt string //
}

func NewShoppingCartInfoDao() *ShoppingCartInfoDao {
	return &ShoppingCartInfoDao{
		M:     g.DB("default").Model("shopping_cart_info").Safe(),
		DB:    g.DB("default"),
		Table: "shopping_cart_info",
		Columns: shoppingCartInfoColumns{
			Id:        "id",
			UserId:    "user_id",
			GoodsId:   "goods_id",
			Count:     "count",
			CreatedAt: "created_at",
			UpdatedAt: "updated_at",
		},
	}
}
