// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// UserCouponInfoDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type UserCouponInfoDao struct {
	gmvc.M                        // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB                // DB is the raw underlying database management object.
	Table   string                // Table is the table name of the DAO.
	Columns userCouponInfoColumns // Columns contains all the columns of Table that for convenient usage.
}

// UserCouponInfoColumns defines and stores column names for table user_coupon_info.
type userCouponInfoColumns struct {
	Id        string // 用户优惠券表
	UserId    string //
	CouponId  string //
	Status    string // 状态：1可用 2已用 3过期
	CreatedAt string //
	UpdatedAt string //
	DeletedAt string //
}

func NewUserCouponInfoDao() *UserCouponInfoDao {
	return &UserCouponInfoDao{
		M:     g.DB("default").Model("user_coupon_info").Safe(),
		DB:    g.DB("default"),
		Table: "user_coupon_info",
		Columns: userCouponInfoColumns{
			Id:        "id",
			UserId:    "user_id",
			CouponId:  "coupon_id",
			Status:    "status",
			CreatedAt: "created_at",
			UpdatedAt: "updated_at",
			DeletedAt: "deleted_at",
		},
	}
}
